steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/csci-5409new/my-repo/container2:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/csci-5409new/my-repo/container2:latest']
images:
  - 'us-central1-docker.pkg.dev/csci-5409new/my-repo/container2:latest'

options:
  logging: 'NONE'  # No logs generated
